# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

# Custom config

set -o vi
bind -m vi-insert "\C-l":clear-screen

function title()
{
    export PROMPT_COMMAND="echo -ne '\033]0;$1\a'"
}

export PROMPT_DIRTRIM=2
export PS1="[\w]\$ "

export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big big history
export HISTFILESIZE=100000               # big big history
shopt -s histappend                      # append to history, don't overwrite it

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export EDITOR="nvim"

alias vi=nvim
alias vim=nvim
alias more="less -R"
alias docker="podman"

eval "$(zoxide init bash)"
eval "$(fzf --bash)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

[[ $- != *i* ]] && return
. "$HOME/.cargo/env"
