# theme = "yo_light"
theme = "zenbones"

[editor]
# end-of-line-diagnostics = "hint"
popup-border = "all"
cursorline = true
lsp.display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning" 
# other-lines = "disable"
